---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Fetch WordPress security keys
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: wp_salt_keys

- name: Generate wp-config.php using Jinja2 template
  template:
    src: wp-config.php.j2
    dest: /tmp/wordpress/wp-config.php
  vars:
    wp_salt: "{{ wp_salt_keys.content }}"

- name: Copy WordPress files to /var/www/html
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes
    owner: apache
    group: apache
    mode: '0755'

- name: Download wp-cli
  get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "/usr/local/bin/wp"
    mode: '0755'

- name: Ensure wp-cli is executable
  file:
    path: "/usr/local/bin/wp"
    mode: '0755'
    state: file

- name: Run WordPress installation as root
  command: >
    wp core install 
    --url="{{ wp_site_url }}" 
    --title="{{ wp_site_title }}" 
    --admin_user="{{ wp_admin_user }}" 
    --admin_password="{{ wp_admin_password }}" 
    --admin_email="{{ wp_admin_email }}"
  args:
    chdir: "/var/www/html"
  become: yes

- name: Ensure ownership of WordPress files
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: apache
    group: apache
  become: yes

- name: Restart Apache
  service:
    name: httpd
    state: restarted
