---
- name: Enable Amazon Linux Extras for PHP 7.4
  command: amazon-linux-extras enable php7.4

- name: Clean YUM metadata
  command: yum clean metadata

- name: Install the latest PHP version and required extensions
  yum:
    name:
      - php
      - php-cli
      - php-common
      - php-mysqlnd
      - php-json
      - php-xml
      - php-mbstring
      - php-gd
      - php-curl
      - php-fpm  # Ensure PHP-FPM is installed
    state: latest

- name: Start and enable PHP-FPM
  service:
    name: php-fpm
    state: started
    enabled: true

